#!/bin/bash

# This is a simple hook executed after your application has stopped.
# This script gets executed directly, so it could be python, php, ruby, etc.
# Environment variables: $SITE_HOME $APP_HOME $APP_PYTH_ENV $APP_REPO_DIR
